name: Reassure Performance Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths-ignore: ['**.md', '**.sh']

jobs:
  # Note: We run baseline and delta performance checks in the same runner to reduce hardware variance across machines
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest
    steps:
      # v4
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # v4
      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version-file: '.nvmrc'

      - name: Run Reassure baseline tests
        shell: bash
        run: |
          BASELINE_BRANCH=${BASELINE_BRANCH:="main"}
          git fetch origin "$BASELINE_BRANCH" --no-tags --depth=1
          git switch "$BASELINE_BRANCH"
          npm install --force || (rm -rf node_modules && npm install --force) 
          NODE_OPTIONS=--experimental-vm-modules npx reassure --baseline

      - name: Run Reassure delta tests
        shell: bash
        run: |
          git switch --force --detach -
          git merge --no-commit --allow-unrelated-histories "$BASELINE_BRANCH" -X ours
          git checkout --ours .
          npm install --force || (rm -rf node_modules && npm install --force)
          NODE_OPTIONS=--experimental-vm-modules npx reassure --branch

      - name: Validate output.json
        id: validateReassureOutput
        uses: ./.github/actions/javascript/validateReassureOutput
        with:
          DURATION_DEVIATION_PERCENTAGE: 20
